# Generated by Django 3.0.6 on 2020-05-21 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelareageografica',
            name='num_nag_nivel',
            field=models.IntegerField(db_column='Nivel', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
