# Generated by Django 3.0.6 on 2020-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambitos',
            name='bool_eliminado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoobjetivo',
            name='bool_eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
