# Generated by Django 3.0.6 on 2020-05-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0003_auto_20200518_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id_Estructura', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Nombre', models.CharField(max_length=256)),
            ],
        ),
    ]
