# Generated by Django 3.0.6 on 2020-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0004_estructura'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructura',
            name='bool_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
