# Generated by Django 3.0.6 on 2020-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0005_estructura_bool_eliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id_Riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Nombre', models.CharField(max_length=256)),
                ('bool_eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
