# Generated by Django 3.0.6 on 2020-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0008_nivel_area_geografica_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel_area_geografica',
            old_name='bool_NG_Eliminado',
            new_name='bool_NG_eliminado',
        ),
    ]
