# Generated by Django 3.0.6 on 2020-05-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0011_auto_20200519_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambitos',
            new_name='Ambito',
        ),
    ]
