# Generated by Django 3.0.6 on 2020-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambitos',
            fields=[
                ('id_Ambito', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Nombre', models.CharField(max_length=256)),
                ('Str_Descripcion', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id_Tipo_Objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Nombre', models.CharField(max_length=256)),
            ],
        ),
    ]
