# Generated by Django 3.0.6 on 2020-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0002_auto_20200518_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambitos',
            name='bool_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
