# Generated by Django 3.0.6 on 2020-05-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0006_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInterviniente',
            fields=[
                ('id_Tipo_Interviniente', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Nombre', models.CharField(max_length=256)),
                ('bool_eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
