# Generated by Django 3.0.6 on 2020-05-19 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0007_tipointerviniente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Area_Geografica',
            fields=[
                ('id_Nivel_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Num_NG_Nivel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Str_NG_Nombre', models.CharField(max_length=256)),
                ('Str_NG_Descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('bool_NG_Eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_Sector', models.AutoField(primary_key=True, serialize=False)),
                ('Str_Sc_Nombre', models.CharField(max_length=256)),
                ('Str_Sc_Descripcion', models.CharField(max_length=256)),
                ('bool_Sc_Eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
