# Generated by Django 3.0.6 on 2020-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0009_auto_20200519_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel_area_geografica',
            old_name='bool_NG_eliminado',
            new_name='bool_NG_Eliminado',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='bool_Sc_Eliminado',
            new_name='bool_Sc_eliminado',
        ),
    ]
