# Generated by Django 3.0.6 on 2020-05-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0010_auto_20200519_1132'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ambitos',
            table='ambitos',
        ),
        migrations.AlterModelTable(
            name='estructura',
            table='estructuras',
        ),
        migrations.AlterModelTable(
            name='nivel_area_geografica',
            table='nivel_areas_geograficas',
        ),
        migrations.AlterModelTable(
            name='riesgo',
            table='riesgos',
        ),
        migrations.AlterModelTable(
            name='sector',
            table='sectores',
        ),
        migrations.AlterModelTable(
            name='tipointerviniente',
            table='tipo_intervinientes',
        ),
        migrations.AlterModelTable(
            name='tipoobjetivo',
            table='tipo_objetivos',
        ),
    ]
