# Generated by Django 3.0.6 on 2020-05-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0012_auto_20200519_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambito',
            old_name='id_Ambito',
            new_name='id_am',
        ),
        migrations.RenameField(
            model_name='estructura',
            old_name='id_Estructura',
            new_name='id_est',
        ),
        migrations.RenameField(
            model_name='nivel_area_geografica',
            old_name='id_Nivel_Area',
            new_name='id_nag',
        ),
        migrations.RenameField(
            model_name='riesgo',
            old_name='id_Riesgo',
            new_name='id_rg',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='id_Sector',
            new_name='id_sc',
        ),
        migrations.RenameField(
            model_name='tipointerviniente',
            old_name='id_Tipo_Interviniente',
            new_name='id_ti',
        ),
        migrations.RenameField(
            model_name='tipoobjetivo',
            old_name='id_Tipo_Objetivo',
            new_name='id_to',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='Str_Descripcion',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='Str_Nombre',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='bool_eliminado',
        ),
        migrations.RemoveField(
            model_name='estructura',
            name='Str_Nombre',
        ),
        migrations.RemoveField(
            model_name='estructura',
            name='bool_eliminado',
        ),
        migrations.RemoveField(
            model_name='nivel_area_geografica',
            name='Num_NG_Nivel',
        ),
        migrations.RemoveField(
            model_name='nivel_area_geografica',
            name='Str_NG_Descripcion',
        ),
        migrations.RemoveField(
            model_name='nivel_area_geografica',
            name='Str_NG_Nombre',
        ),
        migrations.RemoveField(
            model_name='nivel_area_geografica',
            name='bool_NG_Eliminado',
        ),
        migrations.RemoveField(
            model_name='riesgo',
            name='Str_Nombre',
        ),
        migrations.RemoveField(
            model_name='riesgo',
            name='bool_eliminado',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='Str_Sc_Descripcion',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='Str_Sc_Nombre',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='bool_Sc_eliminado',
        ),
        migrations.RemoveField(
            model_name='tipointerviniente',
            name='Str_Nombre',
        ),
        migrations.RemoveField(
            model_name='tipointerviniente',
            name='bool_eliminado',
        ),
        migrations.RemoveField(
            model_name='tipoobjetivo',
            name='Str_Nombre',
        ),
        migrations.RemoveField(
            model_name='tipoobjetivo',
            name='bool_eliminado',
        ),
        migrations.AddField(
            model_name='ambito',
            name='bool_am_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='ambito',
            name='str_am_descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ambito',
            name='str_am_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='estructura',
            name='bool_est_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='estructura',
            name='str_est_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='nivel_area_geografica',
            name='bool_nag_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='nivel_area_geografica',
            name='num_nag_nivel',
            field=models.IntegerField(db_column='Nivel', default=9999, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='nivel_area_geografica',
            name='str_nag_descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='nivel_area_geografica',
            name='str_nag_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='bool_rg_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='str_rg_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sector',
            name='bool_sc_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='str_sc_descripcion',
            field=models.CharField(db_column='Descripcion', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sector',
            name='str_sc_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tipointerviniente',
            name='bool_ti_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='tipointerviniente',
            name='str_ti_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tipoobjetivo',
            name='bool_to_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.AddField(
            model_name='tipoobjetivo',
            name='str_to_nombre',
            field=models.CharField(db_column='Nombre', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='ambito',
            name='id_am',
            field=models.AutoField(db_column='id_Ambito', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estructura',
            name='id_est',
            field=models.AutoField(db_column='id_Estructura', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nivel_area_geografica',
            name='id_nag',
            field=models.AutoField(db_column='id_Nivel_Area', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='id_rg',
            field=models.AutoField(db_column='id_Riesgo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='id_sc',
            field=models.AutoField(db_column='id_Sector', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipointerviniente',
            name='id_ti',
            field=models.AutoField(db_column='id_Tipo_Interviniente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoobjetivo',
            name='id_to',
            field=models.AutoField(db_column='id_Tipo_Objetivo', primary_key=True, serialize=False),
        ),
    ]
