# Generated by Django 3.0.6 on 2020-05-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0013_auto_20200521_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAreaGeografica',
            fields=[
                ('id_nag', models.AutoField(db_column='id_Nivel_Area', primary_key=True, serialize=False)),
                ('num_nag_nivel', models.IntegerField(db_column='Nivel', default=9999, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('str_nag_nombre', models.CharField(db_column='Nombre', max_length=256)),
                ('str_nag_descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=256, null=True)),
                ('bool_nag_eliminado', models.BooleanField(db_column='eliminado', default=False)),
            ],
            options={
                'db_table': 'nivel_areas_geograficas',
            },
        ),
        migrations.DeleteModel(
            name='Nivel_Area_Geografica',
        ),
        migrations.AlterField(
            model_name='ambito',
            name='str_am_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='estructura',
            name='str_est_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='str_rg_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='sector',
            name='str_sc_descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='str_sc_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='tipointerviniente',
            name='str_ti_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='tipoobjetivo',
            name='str_to_nombre',
            field=models.CharField(db_column='Nombre', max_length=256),
        ),
    ]
